import {
  User,
  Student,
  Room,
  Area,
  ActivitySchedule,
  Violation,
  Coaching,
  Case,
  Appreciation,
  RoomInspection,
  DutyRoster,
  Handover,
  Incident,
  FacilityTicket,
  NotificationItem,
  AuditLog,
  StudentHabitLog,
} from '../src/types.js';

export const initialUsers: User[] = [
  {
    id: 'u-1',
    name: 'Ust. Ahmad Fauzi',
    email: 'ahmad@almaa.sch.id',
    role: 'PENGASUH',
    roleLabel: 'Pengasuh / Musyrif Kamar 01 & 04',
    phone: '0812-3456-7890',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    assignedRoomIds: ['room-1', 'room-4'],
  },
  {
    id: 'u-2',
    name: 'Ust. Ridwan Kamiludin, M.Pd.',
    email: 'ridwan@almaa.sch.id',
    role: 'KOORDINATOR',
    roleLabel: 'Koordinator Pengasuhan Almaa',
    phone: '0813-9876-5432',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    assignedRoomIds: ['room-1', 'room-2', 'room-3', 'room-4'],
  },
  {
    id: 'u-3',
    name: 'Ust. Budi Prasetyo, S.Sos.',
    email: 'budi@almaa.sch.id',
    role: 'PENGASUH',
    roleLabel: 'Pengasuh / Musyrif Kamar 02',
    phone: '0812-7777-8888',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    assignedRoomIds: ['room-2'],
  },
  {
    id: 'u-4',
    name: 'Ust. Candra Wijaya, S.Pd.',
    email: 'candra@almaa.sch.id',
    role: 'PENGASUH',
    roleLabel: 'Pengasuh / Musyrif Kamar 03',
    phone: '0812-4444-5555',
    avatar: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=150&auto=format&fit=crop&q=80',
    assignedRoomIds: ['room-3'],
  },
  {
    id: 'u-5',
    name: 'K.H. Abdullah Syafi\'i',
    email: 'pimpinan@almaa.sch.id',
    role: 'PIMPINAN',
    roleLabel: 'Pimpinan Pondok Pesantren Almaa',
    phone: '0811-1222-3333',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80',
    assignedRoomIds: [],
  },
  {
    id: 'u-6',
    name: 'Ustadzah Sarah Aminah, S.Ag.',
    email: 'sarah@almaa.sch.id',
    role: 'GURU',
    roleLabel: 'Dewan Guru Tahfidz & Fiqih',
    phone: '0812-6666-9999',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
    assignedRoomIds: [],
  },
  {
    id: 'u-7',
    name: 'Admin Sistem Almaa',
    email: 'admin@almaa.sch.id',
    role: 'SUPER_ADMIN',
    roleLabel: 'Administrator IT Almaa Care OS',
    phone: '0812-0000-1111',
    avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150&auto=format&fit=crop&q=80',
    assignedRoomIds: ['room-1', 'room-2', 'room-3', 'room-4'],
  },
];

export const initialRooms: Room[] = [
  {
    id: 'room-1',
    number: '01',
    name: 'Kamar Abu Bakar Ash-Shiddiq',
    floor: 1,
    capacity: 6,
    occupantCount: 5,
    supervisorId: 'u-1',
    supervisorName: 'Ust. Ahmad Fauzi',
    headStudentId: 'st-1',
    headStudentName: 'Ahmad Rayhan Firdaus',
    status: 'NORMAL',
    lastInspectionDate: '2026-09-17 05:45',
    scoreClean: 95,
    scoreTidy: 92,
    scoreOrderly: 94,
    scoreSafety: 100,
    averageScore: 95,
    facilities: ['6 Ranjang Tingkat', '6 Lemari Locker', '2 Kipas Angin Dinding', 'Rak Sandal', 'Gantungan Handuk'],
  },
  {
    id: 'room-2',
    number: '02',
    name: 'Kamar Umar bin Khattab',
    floor: 1,
    capacity: 6,
    occupantCount: 5,
    supervisorId: 'u-3',
    supervisorName: 'Ust. Budi Prasetyo',
    headStudentId: 'st-6',
    headStudentName: 'Yusuf Ibrahim Malik',
    status: 'NORMAL',
    lastInspectionDate: '2026-09-17 05:50',
    scoreClean: 88,
    scoreTidy: 86,
    scoreOrderly: 90,
    scoreSafety: 95,
    averageScore: 90,
    facilities: ['6 Ranjang Tingkat', '6 Lemari Locker', '2 Kipas Angin Dinding', 'Rak Sandal', 'Gantungan Handuk'],
  },
  {
    id: 'room-3',
    number: '03',
    name: 'Kamar Utsman bin Affan',
    floor: 2,
    capacity: 6,
    occupantCount: 5,
    supervisorId: 'u-4',
    supervisorName: 'Ust. Candra Wijaya',
    headStudentId: 'st-11',
    headStudentName: 'Umar Syarif Hidayat',
    status: 'NEEDS_ATTENTION',
    lastInspectionDate: '2026-09-17 05:55',
    scoreClean: 72,
    scoreTidy: 68,
    scoreOrderly: 75,
    scoreSafety: 85,
    averageScore: 75,
    facilities: ['6 Ranjang Tingkat', '6 Lemari Locker', '2 Kipas Angin Dinding (1 Mati)', 'Rak Sandal', 'Gantungan Handuk'],
  },
  {
    id: 'room-4',
    number: '04',
    name: 'Kamar Ali bin Abi Thalib',
    floor: 2,
    capacity: 6,
    occupantCount: 5,
    supervisorId: 'u-1',
    supervisorName: 'Ust. Ahmad Fauzi',
    headStudentId: 'st-16',
    headStudentName: 'Abdullah Azzam Hakim',
    status: 'NORMAL',
    lastInspectionDate: '2026-09-16 21:10',
    scoreClean: 90,
    scoreTidy: 88,
    scoreOrderly: 92,
    scoreSafety: 96,
    averageScore: 91,
    facilities: ['6 Ranjang Tingkat', '6 Lemari Locker', '2 Kipas Angin Dinding', 'Rak Sandal', 'Gantungan Handuk'],
  },
];

export const initialStudents: Student[] = [];

export const initialAreas: Area[] = [
  {
    id: 'area-1',
    name: 'Masjid Jami\' Al-Ittihad',
    type: 'IBADAH',
    picId: 'u-1',
    picName: 'Ust. Ahmad Fauzi',
    inspectionSchedule: 'Sebelum & Sesudah Sholat Wajib',
    status: 'BERSIH',
    lastCheckedAt: '2026-09-17 05:30',
    notes: 'Sajadah tertata rapi, mikrofon berfungsi normal.',
  },
  {
    id: 'area-2',
    name: 'Kamar Mandi & Tempat Wudhu Utama',
    type: 'SANITASI',
    picId: 'u-3',
    picName: 'Ust. Budi Prasetyo',
    inspectionSchedule: '06.00 & 17.30',
    status: 'BERSIH',
    lastCheckedAt: '2026-09-17 06:10',
    notes: 'Lantai kering, sabun dan kaporit tersedia.',
  },
  {
    id: 'area-3',
    name: 'Ruang Makan Santri (Dining Hall)',
    type: 'KONSUMSI',
    picId: 'u-4',
    picName: 'Ust. Candra Wijaya',
    inspectionSchedule: 'Setelah Sarapan, Makan Siang & Malam',
    status: 'BERSIH',
    lastCheckedAt: '2026-09-17 07:05',
    notes: 'Meja makan telah disapu dan dipel.',
  },
  {
    id: 'area-4',
    name: 'Gedung Kelas Ibnu Sina',
    type: 'PENDIDIKAN',
    picId: 'u-6',
    picName: 'Ustadzah Sarah Aminah',
    inspectionSchedule: '07.00 & 13.00',
    status: 'BERSIH',
    lastCheckedAt: '2026-09-17 06:55',
    notes: 'Papan tulis bersih, spidol terisi.',
  },
  {
    id: 'area-5',
    name: 'Lapangan Olahraga & Upacara',
    type: 'OUTDOOR',
    picId: 'u-3',
    picName: 'Ust. Budi Prasetyo',
    inspectionSchedule: '16.00 & 18.00',
    status: 'BERSIH',
    lastCheckedAt: '2026-09-16 18:00',
    notes: 'Garis lapangan jelas, bola tersimpan di keranjang.',
  },
  {
    id: 'area-6',
    name: 'Halaman & Koridor Asrama Putra Lantai 1',
    type: 'ASRAMA',
    picId: 'u-1',
    picName: 'Ust. Ahmad Fauzi',
    inspectionSchedule: '05.45 & 21.00',
    status: 'BERSIH',
    lastCheckedAt: '2026-09-17 05:45',
    notes: 'Rak sandal rapi, lantai disapu.',
  },
  {
    id: 'area-7',
    name: 'Koridor Asrama Putra Lantai 2',
    type: 'ASRAMA',
    picId: 'u-4',
    picName: 'Ust. Candra Wijaya',
    inspectionSchedule: '05.45 & 21.00',
    status: 'PERLU_PERHATIAN',
    lastCheckedAt: '2026-09-17 06:00',
    notes: 'Ada jemuran handuk basah di pagar koridor, perlu dipindahkan ke tali jemuran.',
  },
  {
    id: 'area-8',
    name: 'Ruang UKS & Kesehatan',
    type: 'KESEHATAN',
    picId: 'u-2',
    picName: 'Ust. Ridwan Kamiludin',
    inspectionSchedule: '08.00, 14.00, 20.00',
    status: 'BERSIH',
    lastCheckedAt: '2026-09-17 08:00',
    notes: '1 santri (Hasan Basri) sedang istirahat pemulihan demam.',
  },
  {
    id: 'area-9',
    name: 'Dapur Pondok',
    type: 'FASILITAS',
    picId: 'u-2',
    picName: 'Ust. Ridwan Kamiludin',
    inspectionSchedule: '05.00, 11.00, 17.00',
    status: 'BERSIH',
    lastCheckedAt: '2026-09-17 05:00',
    notes: 'Persiapan makan siang santri tepat waktu.',
  },
  {
    id: 'area-10',
    name: 'Perpustakaan & Ruang Belajar Mandiri',
    type: 'PENDIDIKAN',
    picId: 'u-6',
    picName: 'Ustadzah Sarah Aminah',
    inspectionSchedule: '19.00 & 21.00',
    status: 'BERSIH',
    lastCheckedAt: '2026-09-16 21:00',
    notes: 'Kitab tersusun rapi menurut abjad dan disiplin keilmuan.',
  },
];

export const initialActivities: ActivitySchedule[] = [
  {
    id: 'act-1',
    timeStart: '04:00',
    timeEnd: '04:15',
    name: 'Bangun & Qiyamul Lail',
    category: 'IBADAH',
    sopTitle: 'SOP Bangun Tidur & Qiyamul Lail',
    sopItems: [
      { id: 'sop-1-1', label: 'Bel bangun asrama dibunyikan tepat pukul 04.00', completed: true },
      { id: 'sop-1-2', label: 'Pengasuh menyisir setiap kamar memastikan santri bangun', completed: true },
      { id: 'sop-1-3', label: 'Santri melipat selimut dan merapikan bantal', completed: true },
      { id: 'sop-1-4', label: 'Santri membaca doa bangun tidur secara bersama/mandiri', completed: true },
    ],
  },
  {
    id: 'act-2',
    timeStart: '04:15',
    timeEnd: '04:45',
    name: 'Persiapan Subuh & Wudhu',
    category: 'IBADAH',
    sopTitle: 'SOP Wudhu & Menuju Masjid',
    sopItems: [
      { id: 'sop-2-1', label: 'Antrean wudhu berlangsung tertib tanpa bersuara keras', completed: true },
      { id: 'sop-2-2', label: 'Memakai pakaian sholat bersih (baju koko putih / sarung)', completed: true },
      { id: 'sop-2-3', label: 'Sandal diletakkan teratur di rak sandal masjid', completed: true },
      { id: 'sop-2-4', label: 'Santri masuk masjid membaca doa masuk masjid dan sholat tahiyyatul masjid', completed: true },
    ],
  },
  {
    id: 'act-3',
    timeStart: '04:45',
    timeEnd: '05:30',
    name: 'Subuh Berjamaah & Dzikir Pagi',
    category: 'IBADAH',
    sopTitle: 'SOP Subuh Berjamaah & Absensi Masjid',
    sopItems: [
      { id: 'sop-3-1', label: 'Adzan & Iqamah dikumandangkan tepat waktu', completed: true },
      { id: 'sop-3-2', label: 'Shaf sholat lurus dan rapat (dipandu musyrif)', completed: true },
      { id: 'sop-3-3', label: 'Dzikir ba\'da sholat & pembacaan Al-Matsurat pagi khusyuk', completed: true },
      { id: 'sop-3-4', label: 'Checking presensi Subuh oleh musyrif shaf', completed: true },
    ],
  },
  {
    id: 'act-4',
    timeStart: '05:30',
    timeEnd: '06:15',
    name: 'Kebersihan Pagi & Piket Kamar',
    category: 'KEBERSIHAN',
    sopTitle: 'SOP Kebersihan Pagi Almaa',
    sopItems: [
      { id: 'sop-4-1', label: 'Lantai kamar disapu dan dipel bersih', completed: true },
      { id: 'sop-4-2', label: 'Tempat tidur rapi, seprei kencang, bantal tertata', completed: true },
      { id: 'sop-4-3', label: 'Pakaian kotor masuk keranjang cuci, locker pakaian tertutup', completed: true },
      { id: 'sop-4-4', label: 'Sampah kamar dibuang ke bak sampah luar', completed: true },
      { id: 'sop-4-5', label: 'Kamar mandi & tempat wudhu disikat', completed: false },
      { id: 'sop-4-6', label: 'Area piket koridor & halaman depan selesai dibersihkan', completed: true },
    ],
  },
  {
    id: 'act-5',
    timeStart: '06:15',
    timeEnd: '07:00',
    name: 'Mandi & Sarapan Pagi',
    category: 'HARIAN',
    sopTitle: 'SOP Mandi, Sarapan & Adab Makan',
    sopItems: [
      { id: 'sop-5-1', label: 'Mandi bergantian secara tertib dan hemat air', completed: false },
      { id: 'sop-5-2', label: 'Mengenakan seragam sekolah rapi lengkap dengan dasi/peci', completed: false },
      { id: 'sop-5-3', label: 'Antre sarapan pagi di ruang makan secara teratur', completed: false },
      { id: 'sop-5-4', label: 'Makan dengan tangan kanan, duduk tertib, piring dicuci mandiri', completed: false },
    ],
  },
  {
    id: 'act-6',
    timeStart: '07:00',
    timeEnd: '12:00',
    name: 'Kegiatan Belajar Mengajar (KBM)',
    category: 'BELAJAR',
    sopTitle: 'SOP KBM & Disiplin Kelas',
    sopItems: [
      { id: 'sop-6-1', label: 'Santri sudah berada di dalam kelas pukul 06.55', completed: false },
      { id: 'sop-6-2', label: 'Doa pembuka belajar & muroja\'ah juz amma', completed: false },
      { id: 'sop-6-3', label: 'Presensi kelas diisi oleh guru pengampu', completed: false },
      { id: 'sop-6-4', label: 'Santri yang izin sakit tercatat di buku izin musyrif', completed: false },
    ],
  },
  {
    id: 'act-7',
    timeStart: '12:00',
    timeEnd: '13:30',
    name: 'Dzuhur Berjamaah, Makan Siang & Qailulah',
    category: 'IBADAH',
    sopTitle: 'SOP Dzuhur & Qailulah (Istirahat Siang)',
    sopItems: [
      { id: 'sop-7-1', label: 'Adzan Dzuhur tepat waktu di masjid jami\'', completed: false },
      { id: 'sop-7-2', label: 'Sholat Dzuhur berjamaah & ba\'diyah', completed: false },
      { id: 'sop-7-3', label: 'Makan siang tertib di dining hall', completed: false },
      { id: 'sop-7-4', label: 'Qailulah (tidur siang sunnah) 12.45 - 13.30 di kamar masing-masing', completed: false },
    ],
  },
  {
    id: 'act-8',
    timeStart: '13:30',
    timeEnd: '15:00',
    name: 'Kegiatan Siang & Halaqah Quran',
    category: 'BELAJAR',
    sopTitle: 'SOP Halaqah Tahsin & Tahfidz Siang',
    sopItems: [
      { id: 'sop-8-1', label: 'Santri membawa mushaf pojok Al-Quran Almaa', completed: false },
      { id: 'sop-8-2', label: 'Duduk membentuk halaqah bersama ustadz pembimbing', completed: false },
      { id: 'sop-8-3', label: 'Setoran hafalan baru (ziyadah) atau muroja\'ah', completed: false },
      { id: 'sop-8-4', label: 'Buku mutaba\'ah santri ditandatangani ustadz pembimbing', completed: false },
    ],
  },
  {
    id: 'act-9',
    timeStart: '15:00',
    timeEnd: '17:00',
    name: 'Ashar & Aktivitas Mandiri',
    category: 'IBADAH',
    sopTitle: 'SOP Sholat Ashar & Ekstrakurikuler',
    sopItems: [
      { id: 'sop-9-1', label: 'Sholat Ashar berjamaah tepat waktu', completed: false },
      { id: 'sop-9-2', label: 'Kegiatan olahraga / bela diri / pramuka / istirahat terkontrol', completed: false },
      { id: 'sop-9-3', label: 'Santri tetap berada di dalam area pondok (tidak keluar pagar)', completed: false },
    ],
  },
  {
    id: 'act-10',
    timeStart: '17:00',
    timeEnd: '18:30',
    name: 'Mandi Sore & Persiapan Maghrib',
    category: 'HARIAN',
    sopTitle: 'SOP Mandi Sore & Menjelang Maghrib',
    sopItems: [
      { id: 'sop-10-1', label: 'Santri selesai mandi dan sudah berpakaian rapi pukul 17.30', completed: false },
      { id: 'sop-10-2', label: 'Lampu kamar dinyalakan, jendela kamar ditutup', completed: false },
      { id: 'sop-10-3', label: 'Menuju masjid sebelum adzan Maghrib berkumandang', completed: false },
      { id: 'sop-10-4', label: 'Dzikir petang bersama di masjid', completed: false },
    ],
  },
  {
    id: 'act-11',
    timeStart: '18:30',
    timeEnd: '20:00',
    name: 'Kegiatan Malam & Kajian Kitab',
    category: 'BELAJAR',
    sopTitle: 'SOP Kajian Kitab Kuning / Ta\'lim Afkar',
    sopItems: [
      { id: 'sop-11-1', label: 'Kajian kitab bersama Asatidz di selasar masjid', completed: false },
      { id: 'sop-11-2', label: 'Membawa buku catatan & menyimak penjelasan dengan adab', completed: false },
      { id: 'sop-11-3', label: 'Sesi tanya jawab seputar fiqih & adab keseharian', completed: false },
    ],
  },
  {
    id: 'act-12',
    timeStart: '20:00',
    timeEnd: '21:00',
    name: 'Isya Berjamaah & Makan Malam',
    category: 'IBADAH',
    sopTitle: 'SOP Isya & Makan Malam',
    sopItems: [
      { id: 'sop-12-1', label: 'Sholat Isya berjamaah & witir', completed: false },
      { id: 'sop-12-2', label: 'Makan malam tertib di ruang makan', completed: false },
      { id: 'sop-12-3', label: 'Kembali ke asrama mempersiapkan buku pelajaran esok hari', completed: false },
    ],
  },
  {
    id: 'act-13',
    timeStart: '21:00',
    timeEnd: '21:30',
    name: 'Night Checking (Pemeriksaan Malam)',
    category: 'CHECKING',
    sopTitle: 'SOP Night Checking 21.00 Asrama Almaa',
    sopItems: [
      { id: 'sop-13-1', label: 'Seluruh santri berada di kamar masing-masing', completed: false },
      { id: 'sop-13-2', label: 'Presensi fisik headcount setiap santri di atas ranjang', completed: false },
      { id: 'sop-13-3', label: 'Kondisi kesehatan santri dipastikan (apakah ada yang demam/sakit)', completed: false },
      { id: 'sop-13-4', label: 'Kunci gerbang dan lampu luar asrama dipastikan aman', completed: false },
      { id: 'sop-13-5', label: 'Doa bersama sebelum tidur dipimpin ketua kamar', completed: false },
    ],
  },
  {
    id: 'act-14',
    timeStart: '21:30',
    timeEnd: '04:00',
    name: 'Tidur & Istirahat Malam',
    category: 'ISTIRAHAT',
    sopTitle: 'SOP Istirahat Malam Asrama',
    sopItems: [
      { id: 'sop-14-1', label: 'Lampu utama kamar dipadamkan, lampu tidur dinyalakan', completed: false },
      { id: 'sop-14-2', label: 'Tidak ada suara bising / obrolan santri setelah 21.30', completed: false },
      { id: 'sop-14-3', label: 'Musyrif ronda malam bertugas keliling berkala setiap 2 jam', completed: false },
    ],
  },
];

export const initialViolations: Violation[] = [];

export const initialCoachings: Coaching[] = [];

export const initialCases: Case[] = [];

export const initialAppreciations: Appreciation[] = [];

export const initialDutyRoster: DutyRoster[] = [
  {
    id: 'dr-1',
    shift: '04.00–07.00',
    supervisorId: 'u-1',
    supervisorName: 'Ust. Ahmad Fauzi',
    date: '2026-09-17',
    isCurrentShift: true,
  },
  {
    id: 'dr-2',
    shift: '07.00–12.00',
    supervisorId: 'u-3',
    supervisorName: 'Ust. Budi Prasetyo',
    date: '2026-09-17',
    isCurrentShift: false,
  },
  {
    id: 'dr-3',
    shift: '12.00–17.00',
    supervisorId: 'u-4',
    supervisorName: 'Ust. Candra Wijaya',
    date: '2026-09-17',
    isCurrentShift: false,
  },
  {
    id: 'dr-4',
    shift: '17.00–22.00',
    supervisorId: 'u-1',
    supervisorName: 'Ust. Ahmad Fauzi',
    date: '2026-09-17',
    isCurrentShift: false,
  },
  {
    id: 'dr-5',
    shift: '22.00–04.00',
    supervisorId: 'u-3',
    supervisorName: 'Ust. Budi Prasetyo',
    date: '2026-09-17',
    isCurrentShift: false,
  },
];

export const initialHandovers: Handover[] = [
  {
    id: 'ho-1',
    fromSupervisorId: 'u-3',
    fromSupervisorName: 'Ust. Budi Prasetyo',
    toSupervisorId: 'u-1',
    toSupervisorName: 'Ust. Ahmad Fauzi',
    timestamp: '2026-09-17 04:00',
    pendingCoachingCount: 2,
    pendingFacilityCount: 1,
    attentionStudentsCount: 2,
    shiftNotes: 'Malam berlangsung kondusif. Santri Hasan Basri (Kamar 02) demam ringan, sudah diberi obat penurun panas pukul 02.30. Lampu kamar 03 bagian pojok mati, teknisi sudah dilaporkan.',
    acknowledgedAt: '2026-09-17 04:05',
    isAcknowledged: true,
  },
];

export const initialIncidents: Incident[] = [
  {
    id: 'inc-1',
    code: 'INC-202609-001',
    title: 'Korsleting Ringan Stop Kontak Selasar Asrama',
    location: 'Selasar Asrama Putra Lantai 2',
    date: '2026-09-16',
    time: '20:15',
    studentIds: [],
    studentNames: [],
    incidentType: 'Kelistrikan / Keamanan Fasilitas',
    chronology: 'Tercium bau terbakar dari stop kontak dispenser air minum. Musyrif langsung mematikan MCB lantai 2 dan memindahkan dispenser.',
    initialAction: 'MCB panel lantai 2 dimatikan segera, stop kontak diisolasi dengan tanda peringatan bahaya.',
    picId: 'u-1',
    picName: 'Ust. Ahmad Fauzi',
    priority: 'HIGH',
    status: 'RESOLVED',
    resolvedAt: '2026-09-16 20:45',
    resolvedBy: 'Ust. Ahmad Fauzi',
    createdAt: '2026-09-16 20:20',
  },
];

export const initialFacilities: FacilityTicket[] = [
  {
    id: 'fac-1',
    code: 'FAC-0089',
    areaOrRoom: 'Kamar 03 (Lantai 2)',
    issue: 'Lampu penerangan utama kamar mati dan kipas angin berdengung keras.',
    reporterName: 'Ust. Candra Wijaya',
    picTechnician: 'Pak Mamat (Teknisi Sarpras)',
    priority: 'HIGH',
    status: 'OPEN',
    createdAt: '2026-09-16 21:15',
    notes: 'Perlu penggantian fitting lampu LED 18W dan pengecekan bearing kipas.',
  },
  {
    id: 'fac-2',
    code: 'FAC-0088',
    areaOrRoom: 'Tempat Wudhu Masjid',
    issue: 'Keran air nomor 4 bocor menetes terus-menerus.',
    reporterName: 'Ust. Ahmad Fauzi',
    picTechnician: 'Pak Mamat (Teknisi Sarpras)',
    priority: 'MEDIUM',
    status: 'DONE',
    createdAt: '2026-09-15 08:30',
    resolvedAt: '2026-09-15 14:00',
    notes: 'Karet seal keran telah diganti dengan yang baru.',
  },
];

export const initialNotifications: NotificationItem[] = [
  {
    id: 'notif-1',
    title: 'Checking Subuh Selesai',
    message: 'Seluruh santri kamar 01, 02, dan 04 hadir sholat Subuh berjamaah tepat waktu.',
    type: 'SUCCESS',
    timestamp: '05:30',
    read: false,
    actionType: 'attendance',
  },
  {
    id: 'notif-2',
    title: 'Santri Perlu Perhatian',
    message: 'Zaidan Bilal (Kamar 01) terlambat sholat Subuh (catatan ke-3 bulan ini).',
    type: 'WARNING',
    timestamp: '05:15',
    read: false,
    actionType: 'student',
    targetId: 'st-3',
  },
  {
    id: 'notif-3',
    title: 'Kamar Perlu Perhatian',
    message: 'Kamar 03 memperoleh skor 75 (Need Attention) pada inspeksi kebersihan pagi.',
    type: 'ALERT',
    timestamp: '06:05',
    read: false,
    actionType: 'room',
    targetId: 'room-3',
  },
  {
    id: 'notif-4',
    title: '2 Pembinaan Sedang Berjalan',
    message: 'Pembinaan Zaidan Bilal dan Salman Al-Farisi belum ditutup. Target evaluasi pekan ini.',
    type: 'INFO',
    timestamp: '06:15',
    read: true,
    actionType: 'coaching',
  },
];

export const initialAuditLogs: AuditLog[] = [
  {
    id: 'log-1',
    who: 'Ust. Ahmad Fauzi',
    role: 'PENGASUH',
    what: 'Menyelesaikan SOP Kebersihan Pagi & Checking Kamar 01',
    when: '2026-09-17 05:45:12',
    where: 'Kamar 01',
    before: 'Status: PENDING',
    after: 'Status: SOP COMPLETE (Skor 95)',
  },
  {
    id: 'log-2',
    who: 'Ust. Ahmad Fauzi',
    role: 'PENGASUH',
    what: 'Mencatat Pelanggaran Disiplin Santri Zaidan Bilal Ramadhan',
    when: '2026-09-17 05:15:30',
    where: 'Masjid Jami\' Al-Ittihad',
    before: '-',
    after: 'Level 2: Terlambat Sholat Subuh (Tindak Lanjut Pembinaan)',
  },
  {
    id: 'log-3',
    who: 'Ust. Budi Prasetyo',
    role: 'PENGASUH',
    what: 'Melakukan Handover Shift Pagi kepada Ust. Ahmad Fauzi',
    when: '2026-09-17 04:05:00',
    where: 'Kantor Pengasuhan',
    before: 'Shift Malam (04.00)',
    after: 'Shift Pagi Diakui (Acknowledged)',
  },
  {
    id: 'log-4',
    who: 'Ust. Candra Wijaya',
    role: 'PENGASUH',
    what: 'Membuat Tiket Kerusakan Fasilitas Kamar 03',
    when: '2026-09-16 21:15:20',
    where: 'Kamar 03',
    before: '-',
    after: 'Tiket FAC-0089: Lampu kamar mati dilaporkan ke teknisi',
  },
];
